version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/html/

  - source: /add.php
    destination: /var/www/html/
    
  - source: /navbar.php
    destination: /var/www/html/
    
  - source: /lambda.php
    destination: /var/www/html/

  - source: /composer.json
    destination: /var/www/html/

  - source: /employees.sql
    destination: /var/www/html/

  - source: /assets/
    destination: /var/www/html/assets/

  - source: /src/
    destination: /var/www/html/src/

hooks:
  AfterInstall:
    - location: scripts/install_script
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root


