#!/bin/bash

sudo apt install apache2

sudo apt update

sudo apt install php php-cli

# Check if composer currently installed
if hash composer; then
  echo "Composer Already Installed"
  echo "You can find it at $(type -p composer)"
  else
  sudo wget https://getcomposer.org/composer.phar
  sudo mv composer.phar /bin/composer
fi
