#!/bin/bash

cp /var/www/config.php /var/www/html/config.php
cp /var/www/client.php /var/www/html/client.php
cd /var/www/html/
sudo composer install
cd /var/www/
chmod +x sqlscript.sh
./sqlscript.sh
cd ~
