#!/bin/bash
sudo apt update

sudo apt install apache2 -y

sudo apt install mysql-server

sudo apt install php php-cli -y

curl -sS https://getcomposer.org/installer | php

sudo mv composer.phar /usr/bin/composer